### ISSUE TITLE
Regarding Adding Questions in Solution.

### ISSUE THREAD

**Issue by AmanChhabra-WGS** [mrprince88/CodeGym#4]
* Solution Seems fine. Could you please add detailed question as comment at the top of every file, so that it becomes more explanatory and helpful to others

* Just one questions. Are these solutions also available in javascript?

**Comment by mrprince88** [comment]
I cannot add questions to the solutions. Those are sole property of Algoexpert. One who buys their product will know which solution refer to which problem.
As for javascript solutions you need to search them elsewhere. Someone might have shared them.
